version: '3.8'

services:
    family-starter_nginx:
        build:
            context: ./nginx
        volumes:
            - ./../:/var/www/
        ports:
            - "80:80"
        networks:
            - family

networks:
    family:
        external: true