version: '3.8'

services:
    family-starter_nginx:
        build:
            context: ./nginx
        volumes:
            - ./../:/var/www/
        ports:
            - "80:80"
        networks:
            - family

    redis:
        image: redis:7.2-alpine
        ports:
            - "36379:6379"
        expose:
            - 6379
        volumes:
            - ./redis_data:/data
        restart: always
        networks:
            family:
                aliases:
                    - redis

networks:
    family:
        external: true